# Site Settings
title:              Atekihcan
author:             Atekihcan
email:              com.atekihcan@gmail.com
description:        "WebGL based applications"
keywords:           "atekihcan, graphics, webgl, opengl, coursera"
logo_location:      "/assets/img/profile.png"
favicon:            "/assets/img/favicon.png"

# Handling Reading
exclude:            ['README.md', 'LICENSE.md']

# Conversion
markdown:           kramdown
kramdown:
    input:          GFM
highlighter:        pygments
excerpt_separator:  <!--more-->

# Serving
url:                "http://atekihcan.github.io"
baseurl:            "/webgl"

# Outputting
permalink:          none

# Google Analytics
google_analytics_id: "UA-57470252-5"

# Default Values
defaults:
  -
    scope:
        path:       ""
        type:       "posts"
    values:
        layout:     "page"
        author:     "Atekihcan"